apiVersion: resume.jefedavis.dev/v1alpha1
kind: Resume
metadata:
  name: jeff-davis
  labels:
    resume.jefedavis.dev/candidate: jeffdavis
  annotations:
    resume.jefedavis.dev/security-clearance: true
    resume.jefedavis.dev/security-clearance-level: ts/sci
spec:
  name: Jeff Davis
  email: mr.JefeDavis@gmail.com
  phoneNumber: +1-605-269-8437
  linkedInURL: https://linkedin.com/in/JefeDavis
  githubURL: https://github.com/JefeDavis
  overview: -|
    Passionate Kubernetes Engineer with automation, design, and architecture
    experience along with strong programming and troubleshooting skills in enterprise
    environments. Self-motivated with not only a desire to learn, but to lead and teach
    others as well. Seeking a professionally challenging environment to engage
    technical and automation skills. 
  coreCompetencies:
    - Virtual and Container technology design, implementation, and troubleshooting
    -	Deep understanding of underlyingdata center concepts and theories
    -	Expert on Automating problems to remove roadblocks and ease operational overhead
    -	Productivity in high pressure situations
    -	Analytical thinking
    -	Written and oral communication
    -	Confidence briefing executive staff
    -	Datacenter design & architecture
    -	Experienced traveler
  skills:
    - Languages:
      -	Golang
      -	PowerShell
      -	Python
      -	Bash
      -	Docker
      -	Helm
      -	GraphQL
      -	Yaml
    -	SCM/CI:
      -	Git
      -	GitHub Actions
      -	GitLab CI
    -	Infrastructure-as-Code:
      -	Terraform
      -	Puppet
      -	Ansible
    -	Container Orchestration:
      -	Kubernetes
      -	Docker Swarm
      -	OpenShift
    -	Serverless:
      -	Knative
      -	OpenFaas
      -	Openshift
    -	Monitoring:
      -	Prometheus
      -	Grafana
      -	Splunk